variables:
  NODE_VERSION: "node:22.19.0-alpine"

include:
  project: 'sandbox/cicd_dry_templates'
  file: 'templates/react_pipeline.yml'

run-image:
  stage: run
  only:
    - tags
  trigger:
    project: sandbox/dockercompose/partmanager
