stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install -g @angular/cli@15.1.6
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/
    expire_in: 2 hours
  cache:
    paths:
      - node_modules/

deploy:
  image: docker:stable
  stage: deploy
  only:
    - master
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
